ARG ES_VERSION
# https://github.com/elastic/elasticsearch-docker
FROM elasticsearch:${ES_VERSION}
ARG ES_VERSION

# IK plugin release hosting migrated to https://release.infinilabs.com/analysis-ik/stable/
# (previously on https://github.com/medcl/elasticsearch-analysis-ik/releases).
# New naming drops the 'v' prefix on the version.
ENV IK_RELEASE=https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-${ES_VERSION}.zip

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ${IK_RELEASE}
