# https://github.com/elastic/elasticsearch-docker
FROM elasticsearch:%%VERSION%%

# https://github.com/medcl/elasticsearch-analysis-ik/releases
ENV IK_RELEASE=https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v%%VERSION%%/elasticsearch-analysis-ik-%%VERSION%%.zip
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch $IK_RELEASE
