name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 7.10.1
          - 7.11.2
          - 7.12.1
          - 7.13.4
          - 7.14.2
          - 7.16.3
          - 7.17.18
          - 8.1.3
          - 8.2.3
          - 8.3.3
          - 8.4.3
          - 8.12.2

    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: 'Dockerfile.template'
        platforms: linux/amd64,linux/arm64
        tags: 'davyinsa/elasticsearch-ik:${{ matrix.version }}'
        build-args: |
          ES_VERSION=${{ matrix.version }}
    - name: Login to ALIYUN CR
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUNCR_USERNAME }}
        password: ${{ secrets.ALIYUNCR_PASSWORD }}
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: "Dockerfile.template"
        tags: "registry.cn-hangzhou.aliyuncs.com/davyin/elasticsearch-ik:${{ matrix.version }}"
        build-args: |
          ES_VERSION=${{ matrix.version }}
