name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - tag: 7.10.1
           Dockerfile: "7.10.1/Dockerfile"
           image: "davyinsa/elasticsearch-ik:7.10.1"
         - tag: 7.11.2
           Dockerfile: "7.11.2/Dockerfile"
           image: "davyinsa/elasticsearch-ik:7.11.2"
         - tag: 7.12.1
           Dockerfile: "7.12.1/Dockerfile"
           image: "davyinsa/elasticsearch-ik:7.12.1"
         - tag: 7.13.4
           Dockerfile: "7.13.3/Dockerfile"
           image: "davyinsa/elasticsearch-ik:7.13.3"
         - tag: 7.14.1
           Dockerfile: "7.13.3/Dockerfile"
           image: "davyinsa/elasticsearch-ik:7.13.3"


    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ${{ matrix.Dockerfile }}
        tags: ${{ matrix.image }}
